// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2NdWsH7mxrC1Vj0LjpK-2DV3X78jozag',
    appId: '1:4623844283:web:f50869ccc27c1d8fcb7a9e',
    messagingSenderId: '4623844283',
    projectId: 'gitnote-7b75a',
    authDomain: 'gitnote-7b75a.firebaseapp.com',
    storageBucket: 'gitnote-7b75a.firebasestorage.app',
    measurementId: 'G-C8E20BBEX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmboiOgt6kfpjhR5e-mFcMJNwIHanjLDU',
    appId: '1:4623844283:android:6c4e8fa1079c7b0acb7a9e',
    messagingSenderId: '4623844283',
    projectId: 'gitnote-7b75a',
    storageBucket: 'gitnote-7b75a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs3JvLaxqP3shGJjVKLk8a6zTMNl5BcTo',
    appId: '1:4623844283:ios:c6f2820c3261852acb7a9e',
    messagingSenderId: '4623844283',
    projectId: 'gitnote-7b75a',
    storageBucket: 'gitnote-7b75a.firebasestorage.app',
    iosBundleId: 'com.example.gitnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs3JvLaxqP3shGJjVKLk8a6zTMNl5BcTo',
    appId: '1:4623844283:ios:c6f2820c3261852acb7a9e',
    messagingSenderId: '4623844283',
    projectId: 'gitnote-7b75a',
    storageBucket: 'gitnote-7b75a.firebasestorage.app',
    iosBundleId: 'com.example.gitnote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2NdWsH7mxrC1Vj0LjpK-2DV3X78jozag',
    appId: '1:4623844283:web:da7faf8b0eb15bd3cb7a9e',
    messagingSenderId: '4623844283',
    projectId: 'gitnote-7b75a',
    authDomain: 'gitnote-7b75a.firebaseapp.com',
    storageBucket: 'gitnote-7b75a.firebasestorage.app',
    measurementId: 'G-0T6S8RVC8J',
  );
}
